apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-apps
  template:
    metadata:
      labels:
        app: todo-apps
    spec:
      containers:
        - name: todo-apps
          image: cupaxxhd/todo-apps
