apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-apps
  template:
    metadata:
      labels:
        app: todo-apps
    spec:
      containers:
        - name: todo-apps
          image: cupaxxhd/todo-apps #docker image for todo-apps get from docker hub
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          # resources:
          #   requests:
          #     cpu: "10m"
          #     memory: "16Mi"
          #   limits:
          #     cpu: "100m"
          #     memory: "64Mi"
