apiVersion: v1
kind: Service
metadata:
  name: todo-apps-svc
spec:
  type: NodePort
  selector:
    app: todo-apps # This is the app as declared in the deployment.
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3000
