apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: hourly-image-config
data:
  PORT: "3000"
  IMAGE_URL: "https://picsum.photos/1200"
  TODO_SERVICE_URL: "http://todo-apps-svc:2345"
