apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: hourly-image-svc
spec:
  type: ClusterIP
  selector:
    app: hourly-image # This is the app as declared in the deployment.
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
