apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pingpong-cpu-guard
  namespace: exercises
spec:
  metrics:
    - name: namespace-cpu-usage
      interval: 30s
      count: 10
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1765-prometheus.prometheus.svc.cluster.local:9090
          query: |
            scalar(
              sum(
                rate(container_cpu_usage_seconds_total{
                  namespace="exercises",
                  container!="",
                  image!=""
                }[1m])
              )
            )
      successCondition: result < 0.5
