apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
sortOptions:
  order: fifo
images:
- name: PROJECT/IMAGE
  newName: cupaxxhd/todo-apps
  newTag: e527a8a5db1b944377774052b1b7489cf6b6d560
- name: cupaxxhd/todo-apps
  newName: cupaxxhd/todo-apps
  newTag: 90260897515420b3e52eeb4a5a3791d422292be2
