apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
sortOptions:
  order: fifo
images:
  - name: PROJECT/IMAGE
    newName: cupaxxhd/todo-apps
