apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: exercises
  name: greeter-route
spec:
  parentRefs:
    - kind: Service
      name: greeter-svc
      namespace: exercises
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: greeter-svc-v1
          port: 3000
          weight: 75
        - name: greeter-svc-v2
          port: 3000
          weight: 25
