apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - pv-claim.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - route.yaml
images:
  - name: PROJECT/IMAGE
    newName: cupaxxhd/hourly-image
    newTag: f01053a0c17d83c771db8727d7e908088de11c3f
