apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../manifests/deployment.yaml
patches:
  - target:
      kind: Deployment
      name: broadcaster
sortOptions:
  order: fifo
images:
  - name: PROJECT/IMAGE
    newName: cupaxxhd/broadcaster
