apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
sortOptions:
  order: fifo
images:
- name: PROJECT/IMAGE
  newName: cupaxxhd/hourly-image
- name: cupaxxhd/hourly-image
  newName: cupaxxhd/hourly-image
  newTag: 6f9923687710d8fa5d724e7fbd3ca9db3380f3cf
