apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ./../../manifests/deployment.yaml
patches:
  - target:
      kind: Deployment
      name: broadcaster
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STAGING_MODE
          value: "true"
sortOptions:
  order: fifo
images:
  - name: PROJECT/IMAGE
    newName: cupaxxhd/broadcaster
