apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # Define volume
        - name: log-output
          emptyDir: {}
        - name: config-volume # Define ConfigMap volume
          configMap:
            name: log-output-config
      containers:
        - name: log-output-reader
          image: cupaxxhd/log-output-reader
          env: # Set environment variable from ConfigMap
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts: # Mount volume
            - name: log-output
              mountPath: /src/app/files

            - name: config-volume
              mountPath: /src/app/config
              readOnly: true
          # readinessProbe:
          #   httpGet:
          #     path: /pingpong
          #     port: 3000
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   failureThreshold: 3
        # - name: log-output-writer
        #   image: cupaxxhd/log-output-writer
        #   volumeMounts: # Mount volume
        #     - name: log-output
        #       mountPath: /src/app/files
