apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # Define volume
        - name: shared-storage
          persistentVolumeClaim:
            claimName: pingpong-logoutput-pvc
      containers:
        - name: log-output-reader
          image: cupaxxhd/log-output-reader
          volumeMounts: # Mount volume
            - name: shared-storage
              mountPath: /src/app/files
        - name: log-output-writer
          image: cupaxxhd/log-output-writer
          volumeMounts:
            - name: shared-storage
              mountPath: /src/app/files
