apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: log-output-svc
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  type: ClusterIP
  selector:
    app: log-output # This is the app as declared in the deployment.
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
