apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
sortOptions:
  order: fifo
images:
- name: PROJECT/IMAGE
  newName: cupaxxhd/hourly-image
  newTag: e527a8a5db1b944377774052b1b7489cf6b6d560
- name: cupaxxhd/hourly-image
  newName: cupaxxhd/hourly-image
  newTag: 4bd81fd0114a3d0d45ceaa3847664d2b436df5fd
