apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
sortOptions:
  order: fifo
images:
  - name: PROJECT/IMAGE
    newName: cupaxxhd/broadcaster
    newTag: e2fc63af137a8d6f555540f963af62b47b1fbc20
