apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/postgres-secret.yaml
- manifests/postgres-stful.yaml
- manifests/postgres-service.yaml
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
sortOptions:
  order: fifo
images:
- name: PROJECT/IMAGE
  newName: cupaxxhd/todo-apps
  newTag: f01053a0c17d83c771db8727d7e908088de11c3f
