name: Build and publish application

on:
  push:
    branches: [master]
    tags: ["*"]

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #==============================Starting Build & Push Image==============================
      - name: Build and publish hourly-image
        run: |-
          docker build --tag "cupaxxhd/hourly-image:$GITHUB_SHA" .
          docker push "cupaxxhd/hourly-image:$GITHUB_SHA"
        working-directory: hourly-image

      - name: Build and publish todo-apps
        run: |-
          docker build --tag "cupaxxhd/todo-apps:$GITHUB_SHA" .
          docker push "cupaxxhd/todo-apps:$GITHUB_SHA"
        working-directory: todo-apps

      - name: Build and publish broadcaster
        run: |-
          docker build --tag "cupaxxhd/broadcaster:$GITHUB_SHA" .
          docker push "cupaxxhd/broadcaster:$GITHUB_SHA"
        working-directory: broadcaster
      #==============================Finishing Build & Push Image==============================

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      # #==============================Starting Clone Repo config==============================
      # - name: Clone config repository
      #   run: |
      #     git clone https://x-access-token:${{ secrets.CONFIG_REPO_PAT }}@github.com/CUPAXX/kubernetestraining-config.git
      #     cd kubernetestraining-config
      #     git config user.name "github-actions"
      #     git config user.email "github-actions@github.com"
      # #==============================Finishing Clone Repo config==============================

      #==============================starting update image for staging==============================
      - name: Update manifests Image staging
        if: github.ref == 'refs/heads/master'
        env:
          PAT: ${{ secrets.CONFIG_REPO_PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/CUPAXX/kubernetestraining-config.git
          cd kubernetestraining-config

          cd broadcaster/overlays/staging
          kustomize edit set image cupaxxhd/broadcaster=cupaxxhd/broadcaster:$GITHUB_SHA
          cd -

          cd todo-apps/overlays/staging
          kustomize edit set image cupaxxhd/todo-apps=cupaxxhd/todo-apps:$GITHUB_SHA
          cd -

          cd hourly-image/overlays/staging
          kustomize edit set image cupaxxhd/hourly-image=cupaxxhd/hourly-image:$GITHUB_SHA
          cd -

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Deploy staging ${GITHUB_SHA}"
          git push
      #==============================finishing update image for staging==============================
      #==============================starting update image for production==============================
      - name: Update manifests Image production
        if: startsWith(github.ref, 'refs/tags/')
        env:
          PAT: ${{ secrets.CONFIG_REPO_PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/CUPAXX/kubernetestraining-config.git
          cd kubernetestraining-config

          cd broadcaster/overlays/production
          kustomize edit set image cupaxxhd/broadcaster=cupaxxhd/broadcaster:$GITHUB_SHA
          cd -

          cd todo-apps/overlays/production
          kustomize edit set image cupaxxhd/todo-apps=cupaxxhd/todo-apps:$GITHUB_SHA
          cd -

          cd hourly-image/overlays/production
          kustomize edit set image cupaxxhd/hourly-image=cupaxxhd/hourly-image:$GITHUB_SHA
          cd -

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Deploy production ${GITHUB_SHA}"
          git push
      #==============================finishing update image for production==============================
