name: Build and publish application

on:
  push:

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish hourly-image
        run: |-
          docker build --tag "cupaxxhd/hourly-image:$GITHUB_SHA" .
          docker push "cupaxxhd/hourly-image:$GITHUB_SHA"
        working-directory: hourly-image

      - name: Build and publish todo-apps
        run: |-
          docker build --tag "cupaxxhd/todo-apps:$GITHUB_SHA" .
          docker push "cupaxxhd/todo-apps:$GITHUB_SHA"
        working-directory: todo-apps

      - name: Build and publish broadcaster
        run: |-
          docker build --tag "cupaxxhd/broadcaster:$GITHUB_SHA" .
          docker push "cupaxxhd/broadcaster:$GITHUB_SHA"
        working-directory: broadcaster

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      #==============================starting update image for staging==============================
      - name: Update Image hourly-image staging
        if: github.ref == 'refs/heads/master'
        run: kustomize edit set image cupaxxhd/hourly-image=cupaxxhd/hourly-image:$GITHUB_SHA
        working-directory: hourly-image/overlays/staging

      - name: Update Image todo-apps staging
        if: github.ref == 'refs/heads/master'
        run: kustomize edit set image cupaxxhd/todo-apps=cupaxxhd/todo-apps:$GITHUB_SHA
        working-directory: todo-apps/overlays/staging

      - name: Update Image broadcaster staging
        if: github.ref == 'refs/heads/master'
        run: kustomize edit set image cupaxxhd/broadcaster=cupaxxhd/broadcaster:$GITHUB_SHA
        working-directory: broadcaster/overlays/staging
      #==============================finishing update image for staging==============================

      #==============================starting update image for prod==============================
      - name: Update Image hourly-image production
        if: startsWith(github.ref, 'refs/tags/')
        run: kustomize edit set image cupaxxhd/hourly-image=cupaxxhd/hourly-image:$GITHUB_SHA
        working-directory: hourly-image/overlays/prod

      - name: Update Image todo-apps production
        if: startsWith(github.ref, 'refs/tags/')
        run: kustomize edit set image cupaxxhd/todo-apps=cupaxxhd/todo-apps:$GITHUB_SHA
        working-directory: todo-apps/overlays/prod

      - name: Update Image broadcaster production
        if: startsWith(github.ref, 'refs/tags/')
        run: kustomize edit set image cupaxxhd/broadcaster=cupaxxhd/broadcaster:$GITHUB_SHA
        working-directory: broadcaster/overlays/prod
      #==============================finishing update image for prod==============================

      # - name: Deploy to staging
      #   if: github.ref == 'refs/heads/master'
      #   run: |
      #     kustomize build hourly-image/overlays/staging | kubectl apply -f -
      #     kustomize build todo-apps/overlays/staging | kubectl apply -f -
      #     kustomize build broadcaster/overlays/staging | kubectl apply -f -

      # - name: Deploy to production
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: |
      #     kustomize build hourly-image/overlays/prod | kubectl apply -f -
      #     kustomize build todo-apps/overlays/prod | kubectl apply -f -
      #     kustomize build broadcaster/overlays/prod | kubectl apply -f -

      - name: commit kustomization.yaml to GitHub staging
        if: github.ref == 'refs/heads/master'
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            hourly-image/overlays/staging/kustomization.yaml
            broadcaster/overlays/staging/kustomization.yaml
            todo-apps/overlays/staging/kustomization.yaml
          message: New version released ${{ github.sha }}

      - name: commit kustomization.yaml to GitHub production
        if: startsWith(github.ref, 'refs/tags/')
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            hourly-image/overlays/prod/kustomization.yaml
            broadcaster/overlays/prod/kustomization.yaml
            todo-apps/overlays/prod/kustomization.yaml
          message: New version released ${{ github.sha }}
